/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VpnRouteImport } from './routes/vpn'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as RecsRouteImport } from './routes/recs'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as MylistRouteImport } from './routes/mylist'
import { Route as MusicRouteImport } from './routes/music'
import { Route as MediaRouteImport } from './routes/media'
import { Route as GamesRouteImport } from './routes/games'
import { Route as EmulatorRouteImport } from './routes/emulator'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BrowserRouteImport } from './routes/browser'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as ApiAiChatRouteImport } from './routes/api/ai-chat'

const VpnRoute = VpnRouteImport.update({
  id: '/vpn',
  path: '/vpn',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const RecsRoute = RecsRouteImport.update({
  id: '/recs',
  path: '/recs',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const MylistRoute = MylistRouteImport.update({
  id: '/mylist',
  path: '/mylist',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const EmulatorRoute = EmulatorRouteImport.update({
  id: '/emulator',
  path: '/emulator',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowserRoute = BrowserRouteImport.update({
  id: '/browser',
  path: '/browser',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai-chat',
  path: '/api/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai': typeof AiRoute
  '/apps': typeof AppsRoute
  '/browser': typeof BrowserRoute
  '/chat': typeof ChatRoute
  '/emulator': typeof EmulatorRoute
  '/games': typeof GamesRoute
  '/media': typeof MediaRoute
  '/music': typeof MusicRoute
  '/mylist': typeof MylistRoute
  '/partners': typeof PartnersRoute
  '/recs': typeof RecsRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/vpn': typeof VpnRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai': typeof AiRoute
  '/apps': typeof AppsRoute
  '/browser': typeof BrowserRoute
  '/chat': typeof ChatRoute
  '/emulator': typeof EmulatorRoute
  '/games': typeof GamesRoute
  '/media': typeof MediaRoute
  '/music': typeof MusicRoute
  '/mylist': typeof MylistRoute
  '/partners': typeof PartnersRoute
  '/recs': typeof RecsRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/vpn': typeof VpnRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai': typeof AiRoute
  '/apps': typeof AppsRoute
  '/browser': typeof BrowserRoute
  '/chat': typeof ChatRoute
  '/emulator': typeof EmulatorRoute
  '/games': typeof GamesRoute
  '/media': typeof MediaRoute
  '/music': typeof MusicRoute
  '/mylist': typeof MylistRoute
  '/partners': typeof PartnersRoute
  '/recs': typeof RecsRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/vpn': typeof VpnRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai'
    | '/apps'
    | '/browser'
    | '/chat'
    | '/emulator'
    | '/games'
    | '/media'
    | '/music'
    | '/mylist'
    | '/partners'
    | '/recs'
    | '/security'
    | '/settings'
    | '/shop'
    | '/vpn'
    | '/api/ai-chat'
    | '/api/generate-image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ai'
    | '/apps'
    | '/browser'
    | '/chat'
    | '/emulator'
    | '/games'
    | '/media'
    | '/music'
    | '/mylist'
    | '/partners'
    | '/recs'
    | '/security'
    | '/settings'
    | '/shop'
    | '/vpn'
    | '/api/ai-chat'
    | '/api/generate-image'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai'
    | '/apps'
    | '/browser'
    | '/chat'
    | '/emulator'
    | '/games'
    | '/media'
    | '/music'
    | '/mylist'
    | '/partners'
    | '/recs'
    | '/security'
    | '/settings'
    | '/shop'
    | '/vpn'
    | '/api/ai-chat'
    | '/api/generate-image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AiRoute: typeof AiRoute
  AppsRoute: typeof AppsRoute
  BrowserRoute: typeof BrowserRoute
  ChatRoute: typeof ChatRoute
  EmulatorRoute: typeof EmulatorRoute
  GamesRoute: typeof GamesRoute
  MediaRoute: typeof MediaRoute
  MusicRoute: typeof MusicRoute
  MylistRoute: typeof MylistRoute
  PartnersRoute: typeof PartnersRoute
  RecsRoute: typeof RecsRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  ShopRoute: typeof ShopRoute
  VpnRoute: typeof VpnRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vpn': {
      id: '/vpn'
      path: '/vpn'
      fullPath: '/vpn'
      preLoaderRoute: typeof VpnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recs': {
      id: '/recs'
      path: '/recs'
      fullPath: '/recs'
      preLoaderRoute: typeof RecsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mylist': {
      id: '/mylist'
      path: '/mylist'
      fullPath: '/mylist'
      preLoaderRoute: typeof MylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emulator': {
      id: '/emulator'
      path: '/emulator'
      fullPath: '/emulator'
      preLoaderRoute: typeof EmulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browser': {
      id: '/browser'
      path: '/browser'
      fullPath: '/browser'
      preLoaderRoute: typeof BrowserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-chat': {
      id: '/api/ai-chat'
      path: '/api/ai-chat'
      fullPath: '/api/ai-chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AiRoute: AiRoute,
  AppsRoute: AppsRoute,
  BrowserRoute: BrowserRoute,
  ChatRoute: ChatRoute,
  EmulatorRoute: EmulatorRoute,
  GamesRoute: GamesRoute,
  MediaRoute: MediaRoute,
  MusicRoute: MusicRoute,
  MylistRoute: MylistRoute,
  PartnersRoute: PartnersRoute,
  RecsRoute: RecsRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  ShopRoute: ShopRoute,
  VpnRoute: VpnRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
